name: WFC Build and upload artifact

on: 
  push: 
    branches: [build]
  pull_request:
    branches: [build]
    
jobs:
  build:
    name: Build windows artifact
    runs-on: ubuntu-latest
    steps:           
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
      
#      # Get build version
#      - name: Get build version
#        run: |
#          cd $GITHUB_WORKSPACE
#          (echo -n "buildVersion=" ; grep -m 1 "bundleVersion: " ProjectSettings/ProjectSettings.asset | cut -c 18- ) >> $GITHUB_ENV

#      # Check for duplicate version
#      - name: Check artifact exists
#        uses: xSAVIKx/artifact-exists-action@v0
#        id: "artifact-exists"
#        with:
#          name: "Build-${{ env.buildVersion }}"
#      # Fail if artifact exists
#      - name: Fail if Build-${{ env.buildVersion }} already exists
#        run: exit 1
#        if: "${{ steps.check_workflow_exists.outputs.exists == 'true' }}"
        
     # Cache
#      - uses: actions/cache@v3
#        with:
#          path: Library
#          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
#          restore-keys: |
#            Library-

      # Test
#      - name: Run tests
#        uses: game-ci/unity-test-runner@v4
#        env:
#          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
#          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
#          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
#        with:
#          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Build windows
      - name: Build project
        id: myBuildStep
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          allowDirtyBuild: true
          versioning: Semantic
          
      # Output
      - uses: actions/upload-artifact@v4
        with:
          name: Windows-${{ steps.myBuildStep.outputs.buildVersion  }}
          path: build
          compression-level: 9 # maximum compression
          retention-days: 3
            
#      # Clean up
#      - name: Clean Up after failed build # if we don't do this, the next build will fail
#        if: always()
#        uses: AutoModality/action-clean@v1.1.0